[package]
name = "json_schema_codegen"
version = "0.2.2"
edition = "2021"
description = "JSON Schema code generation utilities"
repository = "https://github.com/ostrowr/jsoncompat"
license = "MIT"
readme = "README.md"

[dependencies]
serde_json = "1.0.135"
thiserror = "2.0.11"
